# Generated by Django 2.2.19 on 2021-11-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211107_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
